#include "config_master.cpp"
#include "localization.hpp"
#include "dialogs\common.hpp"
#include "dialogs\bank_Menu_A.hpp"
#include "dialogs\bank_Menu_B.hpp"
#include "dialogs\bank_Menu_C.hpp"
#include "dialogs\bank_Menu_all.hpp"
#include "dialogs\login.hpp"

#include "dialogs\atm\atm_choice.hpp"
#include "dialogs\atm\atm_gang.hpp"
#include "dialogs\atm\atm_menu_card.hpp"
#include "dialogs\atm\atm_menu_empty.hpp"
#include "dialogs\atm\atm_money.hpp"
#include "dialogs\atm\atm_loading.hpp"
#include "dialogs\atm\atm_stat.hpp"
#include "dialogs\atm\atm_thanks.hpp"
#include "dialogs\atm\atm_transfert.hpp"

#include "dialogs\terminal\terminal.hpp"
#include "dialogs\terminal\terminal_2.hpp"
