// ALF_fnc_interactions_player_to_player_basics = {
// [
// 	[_this,0,objNull,[objNull]] call BIS_fnc_param,
// 	[
// 		["PRESENTER MA CARTE IDENTITE",
// 			"[player,player getVariable [""IdentititeFausse"",profileName]] remoteExecCall [""ALF_fnc_showIDcard"",_t,false];};",
// 			"'ALF_identite' in (magazines player)"],
// 		["PRESENTER MON PERMIS",
// 			"[name player,license_driver,license_trucking,life_permis,license_moto,license_boat,license_pilot] private _t=life_pInact_curObject; if(!isNull _t && {isPlayer _t} && {(owner _t)>=0}) then {remoteExec [""ALF_fnc_showPcard"",_t,false];};",
// 			"'ALF_Permis' in (magazines player)"],
// 		[toupper "démenotter",
// 			"[life_pInact_curObject] call ALF_fnc_unrestrain;",
// 			"[life_pInact_curObject] call ALF_fnc_checkMenotter AND {'ALF_cle_M' in (magazines player)}"],
// 		["LIBERER",
// 			"[life_pInact_curObject] call ALF_fnc_unrestrain2;",
// 			"[life_pInact_curObject] call ALF_fnc_checkMenotter AND {'ALF_ZipCutter' in (magazines player)}"],
			
// 		["ASSIGNER LA CELLULE",
// 			"[4,[],life_pInact_curObject] spawn ALF_fnc_menuMettrePrison;",
// 			"life_penit_service AND {life_pInact_curObject getVariable [""ALF_EnPrison"",false]}"],
// 		["METTRE EN PRISON",
// 			"[0,[],life_pInact_curObject] spawn ALF_fnc_menuMettrePrison;",
// 			"life_penit_service AND {player distance [11052.349,3918.944,0.297] <= 100} AND {!(life_pInact_curObject getVariable [""ALF_EnPrison"",false])}"],
// 		["SORTIR DE PRISON",
// 			"life_pInact_curObject setVariable ['ALF_EnPrison',false,true];",
// 			"life_penit_service AND {player distance [11052.349,3918.944,0.297] <= 100} AND {life_pInact_curObject getVariable [""ALF_EnPrison"",false]}"],
// 		["SOIGNER",
// 			"[life_pInact_curObject] spawn ALF_fnc_soignerPompier;",
// 			"((life_penit_service AND license_medWork) OR life_pompier_service) AND {'ALF_Bandage' in (magazines player)}"],
			
// 		["TEST D'ALCOOLEMIE",
// 			"[player] private _t=life_pInact_curObject; if(!isNull _t && {isPlayer _t} && {(owner _t)>=0}) then {remoteExec [""ALF_fnc_testAlcoolemie"",_t,false];};",
// 			"'ALF_Alcootest' in (magazines player)"],
// 		["TEST DE STUPEFIANTS",
// 			"[player] private _t=life_pInact_curObject; if(!isNull _t && {isPlayer _t} && {(owner _t)>=0}) then {remoteExec [""ALF_fnc_testStup"",_t,false];};",
// 			"'ALF_TestStup' in (magazines player)"],
// 		["METTRE UN BRACELET",
// 			"[0,[],life_pInact_curObject] spawn ALF_fnc_menuAjoutBracelet;",
// 			"'ALF_Bracelet' in (magazines player) AND {!(life_pInact_curObject in (missionNamespace getVariable [""ALF_AllBracelets"",[]]))} AND {life_gendarme_service OR life_penit_service}"],
// 		["ENLEVER LE BRACELET",
// 			"[1,life_pInact_curObject] call ALF_fnc_enleverBracelet;",
// 			"(life_pInact_curObject in (missionNamespace getVariable [""ALF_AllBracelets"",[]])) AND {life_gendarme_service OR life_penit_service}"],
// 		["AMENDE",
// 			"[life_pInact_curObject] call ALF_fnc_ticketAction;",
// 			"life_gendarme_service"],
// 		["VERIFIER CASH",
// 			"[player] remoteExecCall [""ALF_fnc_verifCash"",_t,false];};",
// 			"life_gendarme_service AND {[life_pInact_curObject] call ALF_fnc_checkMenotter OR ([life_pInact_curObject] call ALF_fnc_checkSurrender)}"],
// 		["SAISIR CASH",
// 			"[player] remoteExecCall [""ALF_fnc_saisieCash"",_t,false];};",
// 			"life_gendarme_service AND {[life_pInact_curObject] call ALF_fnc_checkMenotter OR ([life_pInact_curObject] call ALF_fnc_checkSurrender)}"],
// 		["FOUILLER",
// 			"[life_pInact_curObject] spawn ALF_fnc_fouilleAnal;",
// 			"((life_gendarme_service OR life_penit_service) AND {[life_pInact_curObject] call ALF_fnc_checkMenotter}) OR {[life_pInact_curObject] call ALF_fnc_checkSurrender}"],
// 		["TEST ADN",
// 			"[life_pInact_curObject] spawn ALF_fnc_getPlayerAdn;",
// 			"life_gendarme_service"],
// 		["RECONNAISSANCE FACIALE",
// 			"[life_pInact_curObject] spawn ALF_fnc_getPlayerFace;",
// 			"life_gendarme_service"],

// 		["TEST ADN",
// 			"[life_pInact_curObject] spawn ALF_fnc_getPlayerAdn;",
// 			"life_gendarme_service AND (player distance (nearestObject [position player,""Land_mrp_garage""]) < 100 OR {player distance (nearestObject [position player,""Land_mrp_gendarmerie_principale""]) < 100})"],
// 		["RECONNAISSANCE FACIALE",
// 			"[life_pInact_curObject] spawn ALF_fnc_getPlayerFace;",
// 			"life_gendarme_service AND (player distance (nearestObject [position player,""Land_mrp_garage""]) < 100 OR {player distance (nearestObject [position player,""Land_mrp_gendarmerie_principale""]) < 100})"],
		
// 		["ENLEVER LE PERMIS",
// 			"[life_pInact_curObject] call ALF_fnc_actionPoints;",
// 			"life_gendarme_service"],
// 		["ENLEVER DES POINTS",
// 			"[life_pInact_curObject] call ALF_fnc_actionPoints;",
// 			"life_gendarme_service"],
// 		["VERIFIER PERMIS ARMES",
// 			"[player] private _t=life_pInact_curObject; if(!isNull _t && {isPlayer _t} && {(owner _t)>=0}) then {remoteExec [""ALF_fnc_verifParmes"",_t,false];};",
// 			"life_gendarme_service"],
// 		["ENLEVER PERMIS ARMES",
// 			"[2] remoteExecCall [""ALF_fnc_Parmes"",_t,false];}; [""Info"", ""Vous avez retiré le permis port d'armes de la personne."", ""success"", false] spawn ALF_fnc_doMsg;",
// 			"life_gendarme_service AND (licence_Target select 0)"],
		
// 		["GROUPE SANGUIN",
// 			"[0,life_pInact_curObject] spawn ALF_fnc_testGroupeSanguin;",
// 			"life_pompier_service"],
		
// 		["CROCHETER LE BRACELET",
// 			"[0,life_pInact_curObject] spawn ALF_fnc_enleverBracelet;",
// 			"'ALF_Lockpick' in (magazines player) AND {life_pInact_curObject in (missionNamespace getVariable [""ALF_AllBracelets"",[]])}"],
// 		["METTRE LA CAGOULE",
// 			"[life_pInact_curObject] spawn ALF_fnc_headbag_put_action;",
// 			"([life_pInact_curObject] call ALF_fnc_checkMenotter) AND ('ALF_Headbag' in (items player)) AND ((headgear life_pInact_curObject) != 'ALF_Headbag')"],
// 		["RETIRER LA CAGOULE",
// 			"[life_pInact_curObject] spawn ALF_fnc_headbag_take_action;",
// 			"([life_pInact_curObject] call ALF_fnc_checkMenotter) AND ((headgear life_pInact_curObject) isEqualTo 'ALF_Headbag')"],
// 		["DONNER LE PERMIS DE CONDUIRE",
// 			"[2] remoteExecCall [""ALF_fnc_driver"",_t,false];}; [""Info"", ""Vous avez donné le permis de conduire à la personne."", ""success"", false] spawn ALF_fnc_doMsg;",
// 			"!(licence_Target select 2) AND b_15"],
// 		["ENLEVER LE PERMIS DE CONDUIRE",
// 			"[3] remoteExecCall [""ALF_fnc_driver"",_t,false];}; [""Info"", ""Vous avez retiré le permis de conduire de cette personne."", ""success"", false] spawn ALF_fnc_doMsg;",
// 			"(licence_Target select 2) AND b_15"],
// 		["DONNER LA LICENCE PILOTE",
// 			"[2] remoteExecCall [""ALF_fnc_pilot"",_t,false];}; [""Info"", ""Vous avez donné la licence de vol à la personne."", ""success"", false] spawn ALF_fnc_doMsg;",
// 			"!(licence_Target select 1) AND b_15"],
// 		["ENLEVER LA LICENCE PILOTE",
// 			"[3] remoteExecCall [""ALF_fnc_pilot"",_t,false];}; [""Info"", ""Vous avez retiré la licence de vol de cette personne."", ""success"", false] spawn ALF_fnc_doMsg;",
// 			"(licence_Target select 1) AND b_15"],
// 		["FAIRE FACTURE",
// 			"createDialog ""Life_facture"";",
// 			"!(player getVariable [""isEmployed"",""""] isEqualTo """") AND !(life_pompier_service AND life_gendarme_service AND life_penit_service)"],
			
// 		["[P] Virer de la prison",
// 			"[0,player] remoteExecCall [""ALF_fnc_penitSetLevel"",_t,false];};",
// 			"life_penit > 2"],
// 		["[P] Passer S. Stagiaire",
// 			"[1,player] remoteExecCall [""ALF_fnc_penitSetLevel"",_t,false];};",
// 			"life_penit > 1"],
// 		["[P] Passer S. Titulaire",
// 			"[2,player] remoteExecCall [""ALF_fnc_penitSetLevel"",_t,false];};",
// 			"life_penit > 2"],
// 		["[P] Passer S. Principal",
// 			"[3,player] remoteExecCall [""ALF_fnc_penitSetLevel"",_t,false];};",
// 			"life_penit > 3"],
// 		["[P] Passer S. Brigadier",
// 			"[4,player] remoteExecCall [""ALF_fnc_penitSetLevel"",_t,false];};",
// 			"life_penit > 4"],
// 		["[P] Passer S. Brigadier",
// 			"[4,player] remoteExecCall [""ALF_fnc_penitSetLevel"",_t,false];};",
// 			"life_penit > 4"],
// 		["[P] Passer P. Surveillant",
// 			"[5,player] remoteExecCall [""ALF_fnc_penitSetLevel"",_t,false];};",
// 			"life_penit > 5"],
// 		["[P] Passer Major",
// 			"[6,player] remoteExecCall [""ALF_fnc_penitSetLevel"",_t,false];};",
// 			"life_penit > 6"],
// 		["[P] Passer Lieutenant",
// 			"[7,player] remoteExecCall [""ALF_fnc_penitSetLevel"",_t,false];};",
// 			"life_penit > 7"],
// 		["[P] Passer Capitaine",
// 			"[8,player] remoteExecCall [""ALF_fnc_penitSetLevel"",_t,false];};",
// 			"life_penit > 8"],
// 		["[P] Passer Commandant",
// 			"[9,player] remoteExecCall [""ALF_fnc_penitSetLevel"",_t,false];};",
// 			"life_penit > 9"],
// 		["AJOUTER Medecin",
// 			"[""medWork"",player] remoteExecCall [""ALF_fnc_penitSetLic"",_t,false];};",
// 			"life_penit > 8"],
// 		["RETIRER Medecin",
// 			"[""NOmedWork"",player] remoteExecCall [""ALF_fnc_penitSetLic"",_t,false];};",
// 			"life_penit > 8"],
// 		["AJOUTER ERIS",
// 			"[""eris"",player] remoteExecCall [""ALF_fnc_penitSetLic"",_t,false];};",
// 			"life_penit > 8"],
// 		["RETIRER ERIS",
// 			"[""NOeris"",player] remoteExecCall [""ALF_fnc_penitSetLic"",_t,false];};",
// 			"life_penit > 8"],
// 		["AJOUTER CYNO.",
// 			"[""cynoAP"",player] remoteExecCall [""ALF_fnc_penitSetLic"",_t,false];};",
// 			"life_penit > 8"],
// 		["RETIRER CYNO.",
// 			"[""NOcynoAP"",player] remoteExecCall [""ALF_fnc_penitSetLic"",_t,false];};",
// 			"life_penit > 8"],
		
// 		["[G] Virer de la Gendarmerie",
// 			"[0,player] remoteExecCall [""ALF_fnc_copSetLevel"",_t,false];};",
// 			"life_coplevel > 2"],
// 		["[G] Passer Elève Gendarme",
// 			"[1,player] remoteExecCall [""ALF_fnc_copSetLevel"",_t,false];};",
// 			"life_coplevel > 1"],
// 		["[G] Passer Gendarme",
// 			"[2,player] remoteExecCall [""ALF_fnc_copSetLevel"",_t,false];};",
// 			"life_coplevel > 2"],
// 		["[G] Passer MDL-Chef",
// 			"[3,player] remoteExecCall [""ALF_fnc_copSetLevel"",_t,false];};",
// 			"life_coplevel > 3"],
// 		["[G] Passer Adjudant",
// 			"[4,player] remoteExecCall [""ALF_fnc_copSetLevel"",_t,false];};",
// 			"life_coplevel > 4"],
// 		["[G] Passer Adjudant-Chef",
// 			"[5,player] remoteExecCall [""ALF_fnc_copSetLevel"",_t,false];};",
// 			"life_coplevel > 5"],
// 		["[G] Passer Major",
// 			"[6,player] remoteExecCall [""ALF_fnc_copSetLevel"",_t,false];};",
// 			"life_coplevel > 6"],
// 		["[G] Passer Sous-Lieutenant",
// 			"[7,player] remoteExecCall [""ALF_fnc_copSetLevel"",_t,false];};",
// 			"life_coplevel > 7"],
// 		["[G] Passer Lieutenant",
// 			"[8,player] remoteExecCall [""ALF_fnc_copSetLevel"",_t,false];};",
// 			"life_coplevel > 8"],
// 		["[G] Passer Capitaine",
// 			"[9,player] remoteExecCall [""ALF_fnc_copSetLevel"",_t,false];};",
// 			"life_coplevel > 9"],
// 		["[G] Passer Commandant",
// 			"[10,player] remoteExecCall [""ALF_fnc_copSetLevel"",_t,false];};",
// 			"life_coplevel > 10"],
// 		["[G] Passer Lieutenant-Colonel",
// 			"[11,player] remoteExecCall [""ALF_fnc_copSetLevel"",_t,false];};",
// 			"life_coplevel > 11"],
// 		["AJOUTER CYNO.",
// 			"[""CYNO"",player] remoteExecCall [""ALF_fnc_copSetLic"",_t,false];};",
// 			"life_gendarme_service AND {life_copLevel > 6}"],
// 		["RETIRER CYNO.",
// 			"[""NOCYNO"",player] remoteExecCall [""ALF_fnc_copSetLic"",_t,false];};",
// 			"life_gendarme_service AND {life_copLevel > 6}"],
// 		["AJOUTER GIGN",
// 			"[""GIGN"",player] remoteExecCall [""ALF_fnc_copSetLic"",_t,false];};",
// 			"life_gendarme_service AND {life_copLevel > 6}"],
// 		["RETIRER GIGN",
// 			"[""NOGIGN"",player] remoteExecCall [""ALF_fnc_copSetLic"",_t,false];};",
// 			"life_gendarme_service AND {life_copLevel > 6}"],
// 		["AJOUTER PSIG",
// 			"[""PSIG"",player] remoteExecCall [""ALF_fnc_copSetLic"",_t,false];};",
// 			"life_gendarme_service AND {life_copLevel > 6}"],
// 		["RETIRER PSIG",
// 			"[""NOPSIG"",player] remoteExecCall [""ALF_fnc_copSetLic"",_t,false];};",
// 			"life_gendarme_service AND {life_copLevel > 6}"],
// 		["AJOUTER SR",
// 			"[""SR"",player] remoteExecCall [""ALF_fnc_copSetLic"",_t,false];};",
// 			"life_gendarme_service AND {life_copLevel > 6}"],
// 		["RETIRER SR",
// 			"[""NOSR"",player] remoteExecCall [""ALF_fnc_copSetLic"",_t,false];};",
// 			"life_gendarme_service AND {life_copLevel > 6}"],
// 		["AJOUTER PMO",
// 			"[""PMO"",player] remoteExecCall [""ALF_fnc_copSetLic"",_t,false];};",
// 			"life_gendarme_service AND {life_copLevel > 6}"],
// 		["RETIRER PMO",
// 			"[""NOPMO"",player] remoteExecCall [""ALF_fnc_copSetLic"",_t,false];};",
// 			"life_gendarme_service AND {life_copLevel > 6}"],
			
// 		["[P] Virer des Pompiers",
// 			"[0,player] remoteExecCall [""ALF_fnc_medSetLevel"",_t,false];};",
// 			"life_medicLevel > 2"],
// 		["[P] Passer Sapeur",
// 			"[1,player] remoteExecCall [""ALF_fnc_medSetLevel"",_t,false];};",
// 			"life_medicLevel > 1"],
// 		["[P] Passer Sapeur 1ere Cl.",
// 			"[2,player] remoteExecCall [""ALF_fnc_medSetLevel"",_t,false];};",
// 			"life_medicLevel > 2"],
// 		["[P] Passer Caporal",
// 			"[3,player] remoteExecCall [""ALF_fnc_medSetLevel"",_t,false];};",
// 			"life_medicLevel > 3"],
// 		["[P] Passer Caporal-Chef",
// 			"[4,player] remoteExecCall [""ALF_fnc_medSetLevel"",_t,false];};",
// 			"life_medicLevel > 4"],
// 		["[P] Passer Sergent",
// 			"[5,player] remoteExecCall [""ALF_fnc_medSetLevel"",_t,false];};",
// 			"life_medicLevel > 5"],
// 		["[P] Passer Sergent-Chef",
// 			"[6,player] remoteExecCall [""ALF_fnc_medSetLevel"",_t,false];};",
// 			"life_medicLevel > 6"],
// 		["[P] Passer Adjudant",
// 			"[7,player] remoteExecCall [""ALF_fnc_medSetLevel"",_t,false];};",
// 			"life_medicLevel > 7"],
// 		["[P] Passer Adjudant-Chef",
// 			"[8,player] remoteExecCall [""ALF_fnc_medSetLevel"",_t,false];};",
// 			"life_medicLevel > 8"],
// 		["[P] Passer Lieutenant",
// 			"[9,player] remoteExecCall [""ALF_fnc_medSetLevel"",_t,false];};",
// 			"life_medicLevel > 9"],
// 		["[P] Passer Capitaine",
// 			"[10,player] remoteExecCall [""ALF_fnc_medSetLevel"",_t,false];};",
// 			"life_medicLevel > 10"],
// 		["ADD/SUP SAMU",
// 			"[11,player] remoteExecCall [""ALF_fnc_medSetLevel"",_t,false];};",
// 			"life_medicLevel > 8"],
			
// 		["[P] Virer du Service Publique",
// 			"[0,player] remoteExecCall [""ALF_fnc_pubSetLevel"",_t,false];};",
// 			"life_publique > 6"],
// 		["[P] Passer Grade 1",
// 			"[1,player] remoteExecCall [""ALF_fnc_pubSetLevel"",_t,false];};",
// 			"life_publique > 6"],
// 		["[P] Passer Grade 2",
// 			"[2,player] remoteExecCall [""ALF_fnc_pubSetLevel"",_t,false];};",
// 			"life_publique > 6"],
// 		["[P] Passer Grade 3",
// 			"[3,player] remoteExecCall [""ALF_fnc_pubSetLevel"",_t,false];};",
// 			"life_publique > 6"],
// 		["[P] Passer Grade 4",
// 			"[4,player] remoteExecCall [""ALF_fnc_pubSetLevel"",_t,false];};",
// 			"life_publique > 6"],
// 		["[P] Passer Grade 5",
// 			"[5,player] remoteExecCall [""ALF_fnc_pubSetLevel"",_t,false];};",
// 			"life_publique > 6"],
// 		["[P] Passer Grade 6",
// 			"[6,player] remoteExecCall [""ALF_fnc_pubSetLevel"",_t,false];};",
// 			"life_publique > 6"],
// 		["[P] Passer Grade 7",
// 			"[7,player] remoteExecCall [""ALF_fnc_pubSetLevel"",_t,false];};",
// 			"life_publique > 6"],
// 		["[P] Passer Grade 8",
// 			"[8,player] remoteExecCall [""ALF_fnc_pubSetLevel"",_t,false];};",
// 			"life_publique > 7"]
// 	]
// ] spawn ALF_fnc_interactions_create;

// if true exitwith {};
// [] spawn {
// closedialog 0;
// uisleep 2;
// licence_Target = [];
// licence_rankTarget = [];
// [0] remoteExecCall ["ALF_fnc_Parmes",player];
// [player] spawn {
//     waitUntil {!(licence_rankTarget isEqualTo [])};
//     [_this select 0] call ALF_fnc_interactions_player_to_player_basics;
// };
// };
// };