######################################################################################
##																					##
##                    888b     d888      8888888b.       8888888b.                  ##
##                    8888b   d8888      888   Y88b      888   Y88b                 ##
##                    88888b.d88888      888    888      888    888                 ##
##                    888Y88888P888      888   d88P      888   d88P                 ##
##                    888 Y888P 888      8888888P"       8888888P"                  ##
##                    888  Y8P  888      888 T88b        888                        ##
##                    888   "   888      888  T88b       888                        ##
##                    888       888      888   T88b      888                        ##
##																					##                                                                    
##																					##
##								* Config file * 									##
##									  Rem : 										##
##						   - Don't touch "[CONF]" lines								##
##						  - Set value under "[CONF]" line							##
##																	##
######################################################################################



[Core]
C:\sunny
#C:\Users\Administrateur\Documents\GitHub\ALF-to-MRP

[Temp]
C:\sunny\ALF_Core\ALF_Temp
#C:\Users\Administrateur\Documents\GitHub\ALF-to-MRP\ALF_Core\ALF_Temp

[Secret_Key]
75842

[Token]
Fg9!kLp@c3Z1%Vqx#Mnu7$5TbdLq!TYs

[Port]
50873

[NoToken_Functions]

#[Token]
#t9CtyP#6C7EaQPKM7D#KKoQ&RfJYT75$kiTBe?3G

#[Port]
#5080

#[NoToken_Functions]
#ALF_API_getUserInfo
#ALF_API_getUserBan

