/*

Copyright 2023

Association law 1901 "GET YOUR PATH" registred under the RNA W252007073.

Statement form the journal-officiel.gouv.fr : https://www.journal-officiel.gouv.fr/pages/associations-detail-annonce/?q.id=id:202300270403

More information at kainnon@getyourpath.fr

All rights reserved.

*/
#define F(NAME,TARGET) class NAME { \
    allowedTargets = TARGET; \
};
#define JIP(NAME,TARGET) class NAME { \
    allowedTargets = TARGET; \
    jip = 1; \
};

#define ANYONE 0
#define CLIENT 1
#define SERVER 2

class CfgRemoteExec 
{
    class Functions 
    {
        mode = 1;
        jip = 0;
        
        // Rajouté par NorX Aengell pour MRPV2
        // CLIENT
        F(MRPV2_fnc_Interaction_Scanner_IRM,CLIENT)
        F(MRPV2_fnc_Marqueur_Gestion,CLIENT)
        F(MRPV2_fnc_admins_actions,CLIENT)
        F(MRPV2_fnc_Incendie_FX,CLIENT)
        F(MRPV2_fnc_RefreshInventoryForContainer,CLIENT)
        F(ALF_fnc_createFeu,ANYONE)
        F(ALF_fnc_pafSmoke,ANYONE)
        //Tout le monde = ANYONE
        F(MRPV2_fnc_Vehicule_ApplyVehicleDamage,ANYONE)
        

        // SERVEUR
        F(MRPV2_Server_fnc_Littrage_Citerne_Vers_Client,SERVER)
        F(MRPV2_Server_fnc_Littrage_Client_Vers_Citerne_BDD,SERVER)
        F(MRPV2_Server_fnc_Littrage_Creation_Citerne_BDD,SERVER)

        F(MRPV2_Server_fnc_Vehicule_Configurations,SERVER)
        F(MRPV2_Server_fnc_Vehicule_Garage_Ranger_BDD,SERVER)
        F(MRPV2_Server_fnc_Vehicule_Gestion_Dispo_Et_Ajout_BDD,SERVER)
        F(MRPV2_Server_fnc_Vehicule_Garage_Importer_BDD,SERVER)
        F(MRPV2_Server_fnc_Vehicule_Garage_Exporter_BDD,SERVER)

        F(MRPV2_Server_fnc_Admins_Actions,SERVER)

        F(MRPV2_Server_fnc_Divers_Inventaire_Autorisation,SERVER) 
        F(MRPV2_Server_fnc_Divers_Recup_Liste_Maison_Joueur,SERVER)
         class MRPV2_Server_fnc_rebreatherSave    { allowedTargets = 2; };
        class MRPV2_Server_fnc_rebreatherRequest { allowedTargets = 2; };
        class MRPV2_fnc_rebreatherSetRemaining   { allowedTargets = 1; jip = 1; };
        class MRPV2_fnc_rebreatherStation { allowedTargets = 2; };
  
        // Rajouté par GrosPandaGéant pour MRPV2
        // Client
            // Licences
            F(MRPV2_fnc_civSetLic,CLIENT)
        
        //////// 

        /* Client only functions */

        F(ALF_fnc_addTempMarker,CLIENT)
              
        F(ALF_fnc_driver,CLIENT)
        F(ALF_fnc_addVehicle2Chain,CLIENT)
        F(ALF_fnc_menuCamera,CLIENT)
        F(ALF_fnc_returnSearchURLDN,CLIENT)
        F(ALF_fnc_doBfmCrime,CLIENT)
        F(ALF_fnc_menuSMSSR,CLIENT)
        F(ALF_fnc_giveOrdonnance,CLIENT)
		F(alf_fnc_returnCommand,CLIENT)
        F(ALF_fnc_hideObj,CLIENT)
        F(ALF_fnc_impoundMenu,CLIENT)
		F(ALF_fnc_impoundMenuCopSP,CLIENT)
		F(ALF_fnc_impoundMenuPenit,CLIENT)
        F(ALF_fnc_knockedOut,CLIENT)
        F(ALF_fnc_lightHouse,CLIENT)
        F(ALF_fnc_medicRequest,CLIENT)
        F(ALF_fnc_moveIn,CLIENT)
        F(ALF_fnc_pickupMoney,CLIENT)
        F(ALF_fnc_revived,CLIENT)
        F(ALF_fnc_spikeStripEffect,CLIENT)
        F(ALF_fnc_tazeSound,CLIENT)
        F(SOCK_fnc_dataQuery,CLIENT)
        F(SOCK_fnc_noBDD,CLIENT)
        F(SOCK_fnc_insertPlayerInfo,CLIENT)
        F(SOCK_fnc_updateRequest,CLIENT)
        F(SOCK_fnc_requestReceived,CLIENT)
        F(TON_fnc_clientGetKey,CLIENT)
        F(TON_fnc_clientMessage,CLIENT)
        F(TON_fnc_player_query,CLIENT)
        F(ALF_fnc_updateForfait,CLIENT)
		F(ALF_fnc_headbag_put_target,CLIENT)
        F(ALF_fnc_menuNokia,CLIENT)
        F(ALF_fnc_receptionSmsPhone,CLIENT)
        F(ALF_fnc_updateSmsNokia,CLIENT)
        F(ALF_fnc_updateSmsiPhone,CLIENT)
        F(ALF_fnc_updateSmsSony,CLIENT)
        F(ALF_fnc_updateSmsSonyP,CLIENT)
        F(ALF_fnc_updateSmsSonyPM,CLIENT)
        F(ALF_fnc_ringPlayer,CLIENT)
        F(ALF_fnc_afterTransferCompteBancaire,CLIENT)
        F(ALF_fnc_badTransferCompteBancaire,CLIENT)
        F(ALF_fnc_infoTransferCompteBancaire,CLIENT)
        F(ALF_fnc_receiveMoney,CLIENT)
        F(ALF_fnc_licenseCheck,CLIENT)
        F(ALF_fnc_methzone,CLIENT)
		F(ALF_fnc_combatEffect,CLIENT)
        F(ALF_fnc_licensesRead,CLIENT)
        F(ALF_fnc_flashRadar,CLIENT)
        F(ALF_fnc_doMsg,CLIENT)
        F(ALF_fnc_confirmRetrait,CLIENT)
        F(ALF_fnc_resultPlaque,CLIENT)
        F(ALF_fnc_dispoVehicle,CLIENT)
        F(ALF_fnc_doCopCall,CLIENT)
        F(ALF_fnc_doMedCall,CLIENT)
        F(ALF_fnc_resetCall,CLIENT)
        F(ALF_fnc_SonyResultPlaque,CLIENT)
        F(ALF_fnc_getFlashed,CLIENT)
        F(ALF_fnc_radarMenu,CLIENT)
        F(ALF_fnc_handleItem,CLIENT)
        F(ALF_fnc_update1FipSony,CLIENT)
        F(ALF_fnc_update2FipSony,CLIENT)
        F(ALF_fnc_updateTajSony,CLIENT)
        F(ALF_fnc_restrain,CLIENT)
        F(ALF_fnc_saisieCash,CLIENT)
        F(ALF_fnc_verifCash,CLIENT)
        F(ALF_fnc_copSetLevel,CLIENT)
        F(ALF_fnc_medSetLevel,CLIENT)
        F(ALF_fnc_showIDcard,CLIENT)
        F(ALF_fnc_showPcard,CLIENT)
        F(ALF_fnc_adnUpdate,CLIENT)
        F(ALF_fnc_faceUpdate,CLIENT)
        F(ALF_fnc_getPaidBusiness,CLIENT)
        F(ALF_fnc_initBusinessPlayer,CLIENT)
        F(ALF_fnc_impoundMenuBusiness,CLIENT)
        F(ALF_fnc_updateCNGList,CLIENT)
        F(ALF_fnc_ticketPrompt,CLIENT)
        F(ALF_fnc_ticketPromptPenit,CLIENT)
        F(ALF_fnc_ticketPaid,CLIENT)
        F(ALF_fnc_updateCNPList,CLIENT)
        F(ALF_fnc_updateCNPMList,CLIENT)
        F(ALF_fnc_loadLeboncoin,CLIENT)
        F(ALF_fnc_loadAnnonceLeboncoin,CLIENT)
        F(ALF_fnc_annulerLeboncoin,CLIENT)
        F(ALF_fnc_buyLeboncoin,CLIENT)
        F(ALF_fnc_moneyLeboncoin,CLIENT)
        F(ALF_fnc_supprimerLeboncoin,CLIENT)
        F(ALF_fnc_nextPoints,CLIENT)
        F(ALF_fnc_retirerPermis,CLIENT)
        F(ALF_fnc_doBfmO,CLIENT)
        F(ALF_fnc_doBfmC,CLIENT)
        F(ALF_fnc_verifParmes,CLIENT)
        F(ALF_fnc_copSetLic,CLIENT)
        F(ALF_fnc_penitSetLic,CLIENT)
        F(ALF_fnc_kickSystem,CLIENT)
        F(ALF_fnc_copHouseMarker,CLIENT)
        F(ALF_fnc_playSound3D,CLIENT)
        F(ALF_fnc_testAlcoolemie,CLIENT)
        F(ALF_fnc_testStup,CLIENT)
        F(ALF_fnc_medicalItems,CLIENT)
        F(ALF_fnc_scannerSystem,CLIENT)
        F(ALF_fnc_actionTransfertF,CLIENT)
        F(ALF_fnc_payEntreprise,CLIENT)

        F(ALF_fnc_keyGiveDefBill,CLIENT)
		F(ALF_fnc_keyGiveDefRemoveVehicle,CLIENT)
        F(ALF_fnc_keyGiveDefRemoveHouse,CLIENT)
		F(ALF_fnc_updateCashClient,CLIENT)

        F(ALF_fnc_dialogFisc,CLIENT)
        F(ALF_fnc_startCompleteLogger,CLIENT)
        F(ALF_fnc_removeAxaCount,CLIENT)
        F(ALF_fnc_addXP,CLIENT)
        F(ALF_fnc_menuInspectTel,CLIENT)
        F(ALF_fnc_menuAjoutBracelet,CLIENT)
        F(ALF_fnc_Parmes,CLIENT)
        F(ALF_fnc_penitSetLevel,CLIENT)
        F(ALF_fnc_menuMettrePrison,CLIENT)
        F(ALF_fnc_boucleEnPrison,CLIENT)
        F(ALF_fnc_transfertLit,CLIENT)
        F(ALF_fnc_AdminRevived,CLIENT)
        F(ALF_fnc_porterMort,CLIENT)
        F(ALF_fnc_flashbang,CLIENT)
		F(ALF_fnc_iem,CLIENT)
		F(ALF_fnc_stunGrenade,CLIENT)
        F(ALF_fnc_pilot,CLIENT)
        F(ALF_fnc_menuAllPrisonnier,CLIENT)
        F(ALF_fnc_playPoker,CLIENT)
        F(ALF_fnc_endCall,CLIENT)
		F(ALF_fnc_drapMort,CLIENT)
        F(ALF_fnc_SonyLoadCentral,CLIENT)
        F(ALF_fnc_SonyPLoadCentral,CLIENT)
        F(ALF_fnc_SonyPMLoadCentral,CLIENT)
        F(ALF_fnc_SonyPMedMarkers,CLIENT)
        F(ALF_fnc_deathScreen,CLIENT)
        F(ALF_fnc_setVehiclesKeys,CLIENT)
        F(ALF_fnc_initHouses,CLIENT)
        F(ALF_fnc_setPhoneNumber,CLIENT)
        F(crp_fnc_tapshoulder,CLIENT)
        F(ALF_fnc_pubSetLevel,CLIENT)
		F(ALF_fnc_jesusImAlive,CLIENT)
        F(ALF_fnc_receiveMarker,CLIENT)
        F(murshun_cigs_fnc_start_cig,CLIENT)
        F(murshun_cigs_fnc_smoke,CLIENT)
        F(ALF_fnc_volerArgent,CLIENT)
        F(ALF_fnc_testGroupeSanguin,CLIENT)
        F(ALF_fnc_donDuSang,CLIENT)
		F(ALF_fnc_moneyBagHandle,CLIENT)
		F(ALF_fnc_receiveDABCheck,CLIENT)
		F(ALF_fnc_handleDesease,CLIENT)
		F(ALF_fnc_returnCoins,CLIENT)
		F(ALF_fnc_bag_stock,CLIENT)
		F(ALF_fnc_bag_unstock,CLIENT)
		F(ALF_fnc_soin,CLIENT)
		F(ALF_fnc_playBJ,CLIENT)
		F(ALF_fnc_deadOnBreak,CLIENT)
        F(ALF_fnc_customColorMenu,CLIENT)
        F(ALF_fnc_openColorMenu,CLIENT)
        F(ALF_fnc_openPiano,CLIENT)
        F(ALF_fnc_overColorMenu,CLIENT)
        F(ALF_fnc_selectedColorMenu,CLIENT)
        F(ALF_fnc_sandSystem,CLIENT)
        F(ALF_fnc_pecheBateau,CLIENT)
        F(ALF_fnc_paycheck,CLIENT)
		F(ALF_fnc_finFumee,CLIENT)
		F(ALF_fnc_actionFumee,CLIENT)
		F(ALF_fnc_bevirerHouse,CLIENT)
		F(ALF_fnc_virerHouse,CLIENT)
		F(ALF_fnc_eboueur_payerJoueur,CLIENT)
        F(ALF_fnc_taxi_clientAfterSpawn,CLIENT)
        F(ALF_fnc_taxi_clientAfterRanger,CLIENT)
        F(ALF_fnc_taxi_clientAfterOrphanRanger,CLIENT)
        F(ALF_fnc_taxi_clientAfterEnd,CLIENT)
        F(ALF_fnc_taxi_notifyIncomingCall,CLIENT)
        F(ALF_fnc_distrib_clientAfterSpawn,CLIENT)
        F(ALF_fnc_distrib_clientAfterRanger,CLIENT)
        F(ALF_fnc_distrib_clientAfterEnd,CLIENT)
        F(ALF_fnc_busjob_clientAfterSpawn,CLIENT)
        F(ALF_fnc_busjob_clientAfterRanger,CLIENT)
        F(ALF_fnc_busjob_clientAfterEnd,CLIENT)
        F(ALF_fnc_distrib_restockPay,CLIENT)
        F(ALF_fnc_distrib_restockMenu,CLIENT)
        F(ALF_fnc_distrib_restockRefresh,CLIENT)
        F(ALF_fnc_distrib_updateMapMarker,CLIENT)
		F(mrpv2_fnc_mrp_tel_menu_ca_gestion_etat,CLIENT)
		F(mrpv2_fnc_MRP_Tel_Divers_Crea_Liste_Nombre_Appel,CLIENT)
		F(mrpv2_fnc_MRP_Tel_Divers_Fin_Appel_TFAR,CLIENT)
		F(mrpv2_fnc_MRP_Tel_Divers_Suppr_Son,CLIENT)
		F(mrpv2_fnc_MRP_Tel_Menu_Appel_Demande_Info_Dest,CLIENT)
		F(mrpv2_fnc_MRP_Tel_Divers_syncsinglevar,ANYONE)
		F(MRPV2_fnc_MRP_Tel_Menu_Appel_Init_Variables,CLIENT)
		F(mrpv2_fnc_mrp_tel_menu_ca_gestion_couleur_cadre,CLIENT)
		F(mrpv2_fnc_mrp_tel_menu_ca_suppr_cadre,CLIENT)
		F(mrpv2_fnc_mrp_tel_menu_appel_en_cours_crea,CLIENT)
		F(mrpv2_fnc_mrp_tel_divers_debut_appel_tfar,CLIENT)
		F(mrpv2_fnc_mrp_tel_menu_historique_gestion_histo,CLIENT)
		F(mrpv2_fnc_mrp_tel_menu_sms_action_reception,CLIENT)
		F(mrpv2_fnc_mrp_tel_menu_dispatch_gestion_nombre_connex_collegue,CLIENT)
		F(mrpv2_fnc_mrp_tel_menu_ca_action_repondeur,CLIENT)
		F(bis_fnc_objectvar,ANYONE)
		


        /* Event Client/Server*/
        F(MRPV2_fnc_openNoelGift,CLIENT)
        F(MRPV2_fnc_dropNoelGift,CLIENT)
        F(MRPV2_Server_fnc_startNoelServer,SERVER)

        /* Event Client/Server*/

        /* Server only functions */
        //F(bis_fnc_execvm,SERVER)

        F(ALFCore_fnc_checkOnConnect, SERVER)
        F(ALF_Server_fnc_setHCReady, SERVER)

        F(TON_fnc_thunderbolt,SERVER)
        F(TON_fnc_adminInvisible,SERVER)
        F(bis_fnc_debugconsoleexec,SERVER)

        /* === FONCTIONS SERVEUR (utilisees par fallback si HC non connectes) === */
        /* Les fonctions HC tournent localement dans @MRP_HC1/2/3 addons */
        /* Ces fonctions restent sur SERVER pour le fallback */

        // Boucles systeme (fallback serveur)
        F(ALF_Server_fnc_cleanup,SERVER)
        F(ALF_Server_fnc_appleSystem,SERVER)
        F(ALF_Server_fnc_raisinSystem,SERVER)

        // Incendie & Events (fallback serveur)
        F(ALF_Server_fnc_feuForet,SERVER)
        F(ALF_Server_fnc_startEventFire,SERVER)
        F(ALF_Server_fnc_startEventOrgane,SERVER)
        F(ALF_Server_fnc_countService,SERVER)

        // Business & Bourse (fallback serveur)
        F(ALF_Server_fnc_randomEvent,SERVER)

        /* HeadlessClient only functions */
        F(ALF_Server_fnc_laposte_returnHouse,SERVER)
        F(ALF_Server_fnc_placeCamera,SERVER)
        F(ALF_Server_fnc_searchURLDN,SERVER)
        F(ALF_Server_fnc_recupCamera,SERVER)
        F(ALF_Server_fnc_addMobilier,SERVER)
        F(ALF_Server_fnc_addMobilierCop,SERVER)
        F(ALF_Server_fnc_getUnitFromNumberSR,SERVER)
        F(ALF_Server_fnc_serviceIncendie,SERVER)
        F(ALF_Server_fnc_getMSGFromNumber,SERVER)
        F(ALF_Server_fnc_switchCommand,SERVER)
        F(ALF_Server_fnc_playBJ,SERVER)
        F(ALF_Server_fnc_payerDance,SERVER)
        F(ALF_Server_fnc_setparam,SERVER)
        F(ALF_Server_fnc_checkSoin,SERVER)
        F(ALF_Server_fnc_vehicleJobStore,SERVER)
        F(ALF_Server_fnc_jobTime,SERVER)
        F(ALF_Server_fnc_getJobCar,SERVER)
        F(ALF_Server_fnc_switchSlotMachine,SERVER)
		F(ALF_Server_fnc_updateDABDispo,ANYONE) // HC3
		F(ALF_Server_fnc_checkDABDispo,ANYONE) // HC3
		F(ALF_Server_fnc_retraitDAB,ANYONE) // HC3
        F(ALF_Server_fnc_addHouse,SERVER)
        F(ALF_Server_fnc_deleteDBmobilier,SERVER)
        F(ALF_Server_fnc_getVehicles,SERVER)
		F(ALF_Server_fnc_getVehiclesCopSP,SERVER)
		F(ALF_Server_fnc_getVehiclesPenits,SERVER)
        F(ALF_Server_fnc_insertRequest,SERVER)
        F(ALF_Server_fnc_insertVehicle,SERVER)
		F(ALF_Server_fnc_insertVehicleCopSP,SERVER)
		F(ALF_Server_fnc_insertVehiclePenit,SERVER)
        F(ALF_Server_fnc_jailSys,SERVER)
        F(ALF_Server_fnc_queryRequest,SERVER)
        F(ALF_Server_fnc_sellHouse,SERVER)
        F(ALF_Server_fnc_sellHousemobilier,SERVER)
        F(ALF_Server_fnc_spawnVehicle,SERVER)
		F(ALF_Server_fnc_spawnVehicleCopSP,SERVER)
		F(ALF_Server_fnc_spawnVehiclePenit,SERVER)
        F(ALF_Server_fnc_spawnVehicleLock,SERVER)
        F(ALF_Server_fnc_spikeStrip,SERVER)
        F(ALF_Server_fnc_updatePartial,SERVER)
        F(ALF_Server_fnc_updateRequest,SERVER)
        F(ALF_Server_fnc_vehicleCreate,SERVER)
        F(ALF_Server_fnc_vehicleDelete,SERVER)
        F(ALF_Server_fnc_receleurSell,SERVER)
        F(ALF_Server_fnc_vehicleStockAfterSell,SERVER)
        F(ALF_Server_fnc_vehicleStore,SERVER)
		F(ALF_Server_fnc_vehicleStoreCopSP,SERVER)
		F(ALF_Server_fnc_vehicleStorePenit,SERVER)
        F(ALF_Server_fnc_vehicleUpdate,SERVER)
        F(ALF_Server_fnc_receivekeyofServer,SERVER)
        F(ALF_Server_fnc_calculBourse,SERVER)
        F(ALF_Server_fnc_initBourse,SERVER)
        F(ALF_Server_fnc_loggedBourse,SERVER)
		F(ALF_Server_fnc_vehicleTransfert,SERVER)
        F(ALF_Server_fnc_saveBourse,SERVER)
        F(ALF_Server_fnc_updateBourse,SERVER)
        F(ALF_Server_fnc_buyForfait,SERVER)
        F(ALF_Server_fnc_removeForfait,SERVER)
        F(ALF_Server_fnc_updateContactsPhone,SERVER)
        F(ALF_Server_fnc_sendSmsPhone,SERVER)
        F(ALF_Server_fnc_loadSmsNokia,SERVER)
        F(ALF_Server_fnc_loadSmsiPhone,SERVER)
        F(ALF_Server_fnc_loadSmsSony,SERVER)
        F(ALF_Server_fnc_deleteSmsNokia,SERVER)
        F(ALF_Server_fnc_deleteSmsiPhone,SERVER)
        F(ALF_Server_fnc_FirstJoinServer,SERVER)
        F(ALF_Server_fnc_achatCompteBancaire,SERVER)
        F(ALF_Server_fnc_transferExtCompteBancaire,SERVER)
        F(ALF_Server_fnc_cbParametre,SERVER)
        F(ALF_Server_fnc_playSlotMachine,SERVER)
        F(ALF_Server_fnc_getStock,SERVER)
        F(ALF_Server_fnc_insureVehicles,SERVER)
        F(ALF_Server_fnc_recherchePlaque,SERVER)
        F(ALF_Server_fnc_dispoVehicle,SERVER)
        F(ALF_Server_fnc_startDiagnostic,SERVER)
        F(ALF_Server_fnc_startElevator,SERVER)
        F(ALF_Server_fnc_startRepair,SERVER)
        F(ALF_Server_fnc_poserC4,SERVER)
        F(ALF_Server_fnc_poserPc,SERVER)
        F(ALF_Server_fnc_SonyRecherchePlaque,SERVER)
        F(ALF_Server_fnc_setRadarM,SERVER)
        F(ALF_Server_fnc_MaisSystem,SERVER)
        F(ALF_Server_fnc_playTime,SERVER)
        F(ALF_Server_fnc_loadFipSony,SERVER)
        F(ALF_Server_fnc_addFipSony,SERVER)
        F(ALF_Server_fnc_selectFipSony,SERVER)
        F(ALF_Server_fnc_deleteFipSony,SERVER)
        F(ALF_Server_fnc_createTajSony,SERVER)
        F(ALF_Server_fnc_selectTajSony,SERVER)
        F(ALF_Server_fnc_deleteTajSony,SERVER)
        F(ALF_Server_fnc_permisVerif,SERVER)
        F(ALF_Server_fnc_createAdnFace,SERVER)
        F(ALF_Server_fnc_adnCreate,SERVER)
        F(ALF_Server_fnc_adnRecherche,SERVER)
        F(ALF_Server_fnc_faceCreate,SERVER)
        F(ALF_Server_fnc_faceRecherche,SERVER)
        F(ALF_Server_fnc_WeedSystem,SERVER)
        F(ALF_Server_fnc_WeedSystem2,SERVER)
        F(ALF_Server_fnc_WeedVentilation,SERVER)
		F(ALF_Server_fnc_addElement,SERVER)
		F(ALF_Server_fnc_recupMeth,SERVER)
		F(ALF_Server_fnc_startCrystalise,SERVER)
		F(ALF_Server_fnc_startPillon,SERVER)
		F(ALF_Server_fnc_startSynthese,SERVER)
        F(ALF_Server_fnc_logIt,SERVER)
        F(ALF_Server_fnc_ACDiag,SERVER)
        F(ALF_Server_fnc_internetLivSystem,SERVER)
        F(ALF_Server_fnc_livraisonSystem,SERVER)
        F(ALF_Server_fnc_createBusiness,SERVER)
        F(ALF_Server_fnc_agrandirBusiness,SERVER)
        F(ALF_Server_fnc_capitalBusiness,SERVER)
        F(ALF_Server_fnc_getBusinessCapital,SERVER)
        F(ALF_Server_fnc_withdrawBusinessCapital,SERVER)
        F(ALF_Server_fnc_withdrawCapitalBySecteur,SERVER)
        F(ALF_Server_fnc_addCapitalBySecteur,SERVER)
        F(ALF_Server_fnc_recruterBusiness,SERVER)
        F(ALF_Server_fnc_getVehiclesBusiness,SERVER)
        F(ALF_Server_fnc_spawnVehicleBusiness,SERVER)
        F(ALF_Server_fnc_updateCNG,SERVER)
        F(ALF_Server_fnc_retirerCNG,SERVER)
        F(ALF_Server_fnc_deposerCNG,SERVER)
        F(ALF_Server_fnc_listCNG,SERVER)
        F(ALF_Server_fnc_listCNP,SERVER)
        F(ALF_Server_fnc_listCNPM,SERVER)
        F(ALF_Server_fnc_retirerCNP,SERVER)
        F(ALF_Server_fnc_retirerCNPM,SERVER)
        F(ALF_Server_fnc_deposerCNP,SERVER)
        F(ALF_Server_fnc_deposerCNPM,SERVER)
        F(ALF_Server_fnc_updateCNP,SERVER)
        F(ALF_Server_fnc_fonderieFer,SERVER)
        F(ALF_Server_fnc_fonderieCuivre,SERVER)
        F(ALF_Server_fnc_systemeDiamant,SERVER)
        F(ALF_Server_fnc_loadSmsSonyP,SERVER)
        F(ALF_Server_fnc_loadSmsSonyPM,SERVER)
        F(ALF_Server_fnc_mission,SERVER)
        F(ALF_Server_fnc_deleteSmsSonyP,SERVER)
        F(ALF_Server_fnc_deleteSmsSonyPM,SERVER)
        F(ALF_Server_fnc_deleteSmsSony,SERVER)
        F(ALF_Server_fnc_copStoreVehicle,SERVER)
        F(ALF_Server_fnc_pickupAction,SERVER)
        F(ALF_Server_fnc_keyManagement,SERVER)
        F(ALF_Server_fnc_cleanupRequest,SERVER)
        F(ALF_Server_fnc_savePlayerDisconnect,SERVER)
        F(ALF_Server_fnc_getLeboncoin,SERVER)
        F(ALF_Server_fnc_getAnnonceLeboncoin,SERVER)
        F(ALF_Server_fnc_createHouseLeboncoin,SERVER)
        F(ALF_Server_fnc_createVehiculeLeboncoin,SERVER)
        F(ALF_Server_fnc_annulerLeboncoin,SERVER)
        F(ALF_Server_fnc_checkLeboncoin,SERVER)
        F(ALF_Server_fnc_achatLeboncoin,SERVER)
        F(ALF_Server_fnc_supprimerLeboncoin,SERVER)
        F(ALF_Server_fnc_axa,SERVER)
        F(ALF_Server_fnc_vehicleCreateBusiness,SERVER)
        F(ALF_Server_fnc_businesstofisc,SERVER)
        F(ALF_Server_fnc_permisTime,SERVER)
        F(ALF_Server_fnc_vehicleStoreBusiness,SERVER)
        F(ALF_Server_fnc_getVehiclesLock,SERVER)
        F(ALF_Server_fnc_putInFourriere,SERVER)
		F(ALF_Server_fnc_createEpaveVehicle,SERVER)
        F(ALF_Server_fnc_petroleSystem,SERVER)
        F(ALF_Server_fnc_copLogIt,SERVER)
		F(ALF_Server_fnc_drapMortCheck,SERVER)
        F(ALF_Server_fnc_medLogIt,SERVER)
        F(ALF_Server_fnc_medicalo2,SERVER)
        F(ALF_Server_fnc_sonnetteHouse,SERVER)
        F(ALF_Server_fnc_keyGiveTime,SERVER)
		F(ALF_Server_fnc_keyGiveDef,SERVER)
        F(ALF_Server_fnc_updateStation,SERVER)
        F(ALF_Server_fnc_PayToFisc,SERVER)
        F(ALF_Server_fnc_fiscToPlayer,SERVER)
        F(ALF_Server_fnc_braceletElectronique,SERVER)
        F(ALF_Server_fnc_enleverBracelet,SERVER)
        F(ALF_Server_fnc_cocaineInFire,SERVER)
        F(ALF_Server_fnc_fire,SERVER)
        F(ALF_Server_fnc_removeFromHCFire,SERVER)
        F(ALF_Server_fnc_mettrePrison,SERVER)
        F(ALF_Server_fnc_mettreCellule,SERVER)
        F(ALF_Server_fnc_saveCoffre,SERVER)
        F(ALF_Server_fnc_customCoffre,SERVER)
        F(ALF_Server_fnc_poserC4Prison,SERVER)
        F(ALF_Server_fnc_poserC4Barbed,SERVER)
        F(ALF_Server_fnc_sortiePrison,SERVER)
        F(ALF_Server_fnc_updateMobilierInv,SERVER)
        F(ALF_Server_fnc_editSafeCode,SERVER)
        F(ALF_Server_fnc_allPrisonnier,SERVER)
        F(ALF_Server_fnc_playPoker,SERVER)
        F(ALF_Server_fnc_cuireViande,SERVER)
        F(ALF_Server_fnc_callSystem,SERVER)
        F(ALF_Server_fnc_iPhoneTaxiGetAvailable,SERVER)
        F(ALF_Server_fnc_iPhoneTaxiStartCall,SERVER)
        F(ALF_Server_fnc_setVariableServer,SERVER)
        F(ALF_Server_fnc_loadCopCentral,SERVER)
        F(ALF_Server_fnc_loadMedCentral,SERVER)
        F(ALF_Server_fnc_loadPMCentral,SERVER)
        F(ALF_Server_fnc_joinCentral,SERVER)
        F(ALF_Server_fnc_changerPlaque,SERVER)
		F(ALF_Server_fnc_farmingXxX,SERVER)
        F(ALF_Server_fnc_farmingVin,SERVER)
		F(ALF_Server_fnc_farmingPinot,SERVER)
        F(ALF_Server_fnc_farmingJusFraise,SERVER)
        F(ALF_Server_fnc_farmingJusPomme,SERVER)
        F(ALF_Server_fnc_farmingJusRaisin,SERVER)
        F(ALF_Server_fnc_farmingPlanche,SERVER)
        F(ALF_Server_fnc_transformPetrol,SERVER)
        F(ALF_Server_fnc_cocaine,SERVER)
        F(ALF_Server_fnc_recupererPetrole,SERVER)
        F(ALF_Server_fnc_takeWeed,SERVER)
        F(ALF_Server_fnc_doMedCall,SERVER)
        F(ALF_Server_fnc_doCopCall,SERVER)
        F(ALF_Server_fnc_doCopCallWL,SERVER)
        F(ALF_Server_fnc_doPenitCall,SERVER)
        F(ALF_Server_fnc_doRobberyCall,SERVER)
        F(ALF_Server_fnc_createRobberyMarker,SERVER)
        F(ALF_Server_fnc_deathScreen,SERVER)
        F(ALF_Server_fnc_setCameraVar,SERVER)
        F(ALF_Server_fnc_getCameraVar,SERVER)
        F(ALF_Server_fnc_recupHouseData,SERVER)
        F(ALF_Server_fnc_recupMobilierData,SERVER)
        F(ALF_Server_fnc_playSonnetteHouse,SERVER)
        F(ALF_Server_fnc_copBreakDoor,SERVER)
        F(ALF_Server_fnc_poserBaril,SERVER)
        F(ALF_Server_fnc_setAlarmGendarmerie,SERVER)
        F(ALF_Server_fnc_getVehiclesKeys,SERVER)
        F(ALF_Server_fnc_disconnectService,SERVER)
        F(ALF_Server_fnc_priseService,SERVER)
        F(ALF_Server_fnc_fetchPlayerHouses,SERVER)
        F(ALF_Server_fnc_houseCleanup,SERVER)
        F(ALF_Server_fnc_medmarkers,SERVER)
        F(ALF_Server_fnc_bieAllumer,SERVER)
        F(ALF_Server_fnc_bieEteindre,SERVER)
        F(ALF_Server_fnc_biePoserC4,SERVER)
        F(ALF_Server_fnc_biePoserPc,SERVER)
        F(ALF_Server_fnc_bieReparer,SERVER)
        F(ALF_Server_fnc_bieReparerSystem,SERVER)
		F(ALF_Server_fnc_actionLamps,SERVER)
        F(ALF_Server_fnc_fuelVehicule,SERVER)
        F(ALF_Server_fnc_peintureVehicule,SERVER)
        F(ALF_Server_fnc_sendMarker,SERVER)
        F(ALF_Server_fnc_removeMarker,SERVER)
        F(ALF_Server_fnc_systemeSaphir,SERVER)
        F(ALF_Server_fnc_tabacSystem,SERVER)
        F(ALF_Server_fnc_getUnitFromNumber,SERVER)
        F(ALF_Server_fnc_donDuSang,SERVER)
        F(ALF_Server_fnc_saveBanqueSang,SERVER)
        F(ALF_Server_fnc_reparerFeu,SERVER)
		F(ALF_Server_fnc_importVehicleHC,SERVER)
		F(ALF_Server_fnc_importVehicleHCCopSP,SERVER)
		F(ALF_Server_fnc_importVehicleHCPenit,SERVER)
		F(ALF_Server_fnc_bag_vehicle,ANYONE) // HC1
        F(ALF_Server_fnc_addDona,SERVER)
        F(ALF_Server_fnc_addDonaVote,SERVER)
        F(ALF_Server_fnc_spawnAlgues,SERVER)
        F(ALF_Server_fnc_sanctuaireTurtles,SERVER)
        F(ALF_Server_fnc_canneSucreSystem,SERVER)
        F(ALF_Server_fnc_wreckEventStart,SERVER)
        F(ALF_Server_fnc_wreckSpawn,SERVER)
        F(ALF_Server_fnc_rebootSync,SERVER)
        F(ALF_Server_fnc_rebootWeather,SERVER)
        F(ALF_Server_fnc_dirObjEventStart,SERVER)
        F(ALF_Server_fnc_dirObjSpawn,SERVER)
        F(ALF_Server_fnc_pafFlyover,SERVER)
        
        F(ALF_Server_fnc_addHouseBusiness,SERVER)

        
        /* Functions for everyone */
        F(ALF_fnc_animSync,ANYONE)
        F(ALF_fnc_lockVehicle,ANYONE)
        F(ALF_fnc_pullOutVeh,ANYONE)
        F(ALF_fnc_sonnetteHouse,ANYONE)
        F(ALF_fnc_say3D,ANYONE)
        F(ALF_fnc_setFuel,ANYONE)
        F(ALF_fnc_setHPD,ANYONE)
        F(ALF_fnc_fireworksLaunch,ANYONE)
        F(ALF_fnc_updateClientBourse,ANYONE)
        F(ALF_fnc_preReceptionSmsPhone,ANYONE)
        F(ALF_fnc_switchMove,ANYONE)
        F(ALF_fnc_thunderone,ANYONE)
        F(ALF_fnc_thundertwo,ANYONE)
        F(ALF_fnc_weathereffect,ANYONE)
        F(ALF_fnc_deleteKeysTime,ANYONE)
        F(ALF_fnc_setVariable,ANYONE)
        F(BIS_fnc_effectKilledSecondaries,ANYONE)
		F(alf_fnc_debug_remoteexecserver,ANYONE)
        JIP(ALF_fnc_barbecue,ANYONE)
        JIP(ALF_fnc_ambientAnim,ANYONE)
        JIP(ALF_fnc_pistoletEssence,ANYONE)
        JIP(ALF_fnc_updateRope,ANYONE)

        /* Function Rapelling */
        class AR_Client_Rappel_From_Heli { allowedTargets=0; };
    	class AR_Hint { allowedTargets=1; };
    	class AR_Hide_Object_Global { allowedTargets=2; };
    	class AR_Enable_Rappelling_Animation { allowedTargets=2; };
    	class AR_Rappel_From_Heli { allowedTargets=2; };
        class ALF_fnc_respawnTurtle_server { allowedTargets = 2; };
        class ALF_fnc_lockCuffedInVehicle { allowedTargets = 1; jip = 0; }; // 1 = clients
        class ALF_fnc_unlockCuffedInVehicle{ allowedTargets = 1; jip = 0; }
        class ALF_Server_fnc_spawnRentedBoat { allowedTargets = 2; };
        class ALF_Server_fnc_deleteRentedBoat { allowedTargets = 2; };
        class ALF_Server_fnc_spawnRentedCar { allowedTargets = 2; };
        class ALF_Server_fnc_deleteRentedCar { allowedTargets = 2; };
        class ALF_Server_fnc_copHouseMarker { allowedTargets = 2; };
        class ALF_fnc_robberyAlert { allowedTargets = 1; jip = 0; };
        class ALF_fnc_ticketEntreprise { allowedTargets = 1; jip = 1;};

        /* -- RemoteExec system -- */
        F(ALFTools_Server_fnc_receiveRemoteExec, SERVER)
        F(ALFTools_Server_fnc_remoteExec, SERVER)
        F(ALFTools_Client_fnc_receiveRemoteExec, CLIENT)


        F(ALF_fnc_incendie_jetEau,ANYONE)
        F(ALF_fnc_local_delete_fire,CLIENT)
        F(ALF_fnc_local_fire_1,CLIENT)
        F(ALF_fnc_local_fire_2,CLIENT)
        F(ALF_fnc_local_fire_3,CLIENT)
        F(ALF_fnc_steam_fire,CLIENT)
        F(ALF_fnc_incendie_say3D,CLIENT)
        F(alf_server_fnc_burn_poubelle,SERVER)
        F(ALF_Server_fnc_burn_foret,SERVER)
        F(ALF_Server_fnc_burn_building,SERVER)
        F(ALF_Server_fnc_taxiSpawnServiceVehicle,SERVER)
        F(ALF_Server_fnc_taxiEndServiceVehicle,SERVER)
        F(ALF_Server_fnc_taxiRangerVehicle,SERVER)
        F(ALF_Server_fnc_taxiFinishServiceParked,SERVER)
        F(ALF_Server_fnc_distribSpawnServiceVehicle,SERVER)
        F(ALF_Server_fnc_distribRangerVehicle,SERVER)
        F(ALF_Server_fnc_distribFinishServiceParked,SERVER)
        F(ALF_Server_fnc_distribEndServiceVehicle,SERVER)
        F(ALF_Server_fnc_distrib_addStock,SERVER)
        F(ALF_Server_fnc_distrib_stockInit,SERVER)
        F(ALF_Server_fnc_distrib_stockLoad,SERVER)
        F(ALF_Server_fnc_distrib_bddSave,SERVER)
        F(ALF_Server_fnc_distrib_purchaseStock,SERVER)
        F(ALF_Server_fnc_distrib_tryRestock,SERVER)
        F(ALF_Server_fnc_busjobSpawnServiceVehicle,SERVER)
        F(ALF_Server_fnc_busjobRangerVehicle,SERVER)
        F(ALF_Server_fnc_busjobFinishServiceParked,SERVER)
        F(ALF_Server_fnc_busjobEndServiceVehicle,SERVER)
    };

    class Commands {
        mode = 1;
        jip = 1;

        F(arsenal,ANYONE)
        F(lockinventory,ANYONE)
        F(systemchat,ANYONE)
        F(addHandgunItem,ANYONE)
        F(addMagazine,ANYONE)
        F(addPrimaryWeaponItem,ANYONE)
        F(addWeapon,ANYONE)
        F(setFuel,ANYONE)
        F(setHitPointDamage,ANYONE)
        F(enableSimulationGlobal,ANYONE)
        F(enableDynamicSimulation,ANYONE)
        F(switchCamera,ANYONE)
        F(execFSM,ANYONE)
        F(setDir,ANYONE)
        F(playMoveNow,ANYONE)
        F(setUnconscious,ANYONE)
        F(playActionNow,ANYONE)
        F(switchMove,ANYONE)
        F(disableAI,ANYONE)
        F(hideObjectGlobal,ANYONE)
        F(deleteMarkerLocal,ANYONE)
        F(say3D,ANYONE)
        F(removeHeadgear,ANYONE)
        F(lockDriver,ANYONE)
        F(setDamage,ANYONE)
        F(setWind,ANYONE)
        F(playSoundUI,ANYONE)
		F(setvariable,ANYONE)
		F(setvectordirandup,ANYONE)
    };
};